name: Github Postgresql Backup 
on: [push]

jobs: 
  Run-Backup-Script:
    runs-on: ubuntu-latest
    steps:      

      - name: Install SSH key 
        uses: webfactory/ssh-agent@v0.4.1 
        with: 
          ssh-private-key: ${{ secrets.DEPLOY_KEY }} 

      - name: Add key to known_hosts
        run: |
          ssh-keyscan 173.255.252.230 >> ~/.ssh/known_hosts
      

      - name: executing remote ssh commands 
        uses: appleboy/ssh-action@master
        with:
          host: 173.255.252.230          
          port: 22
          key: ${{ secrets.DEPLOY_KEY }}
          script: whoami