name: Github Postgresql Backup 
on: [push]

jobs: 
  Run-Backup-Script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup SSH Keys and known_hosts
        env:
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
            ssh-agent -a $SSH_AUTH_SOCK > /dev/null
            ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"

      - name: Add key to known_hosts
        run: |
          ssh-keyscan 173.255.252.230 >> ~/.ssh/known_hosts

      - name: Add Vault key to environment
        run: echo ${{ secrets.ANSIBLE_VAULT_PASSWORD }} >> ~/.vault_key.txt

      - name: Backup database staging_blocks
        timeout-minutes: 20
        run: ansible-playbook .ansible/playbooks/bbackup.yml -i .ansible/inventories/review/inventory --vault-password-file ~/.vault_key.txt

